language: rust

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b
  - . ~/miniconda3/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 False
  - conda create -q -n starcode starcode -c bioconda
  - conda activate starcode


cache: cargo

addons:
  apt:
    packages:
      - libgsl0-dev
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
